### PR TITLE
Fix vidscraper to work with requests >= 1.0

### PR DESCRIPTION
**Pull request by willkg**
This fixes all the json -> json() calls. Everything in the test suite passes, so I think it's good to go.

### CODE REVIEW

**Comment by melinath** [comment]
The test requirements file needs to be updated. The travis run is failing because it's still installing requests < 1.0.

**Comment by willkg** [comment]
What version do you want to peg it to?

**Comment by melinath** [comment]
Latest is fine with me. 1.2.3?

**Comment by melinath** [comment]
Maybe also remove the commented-out line from setup.py, as long as you're doing another commit anyway?

**Comment by willkg** [comment]
^^^ Nixed the commented out line and updated test_requirements.txt.

**Comment by melinath** [comment]
I'm also concerned that there might be some issues with OAuth handling. I seem to remember that being an issue last time I looked into doing this transition... and the OAuth sections aren't currently covered by the tests. :-p Did you happen to look into that? If not, I'd probably be fine with merging this as-is anyway, and just fixing those issues when they come up.

**Comment by willkg** [comment]
I didn't look into that and don't use the Vimeo support, so it's not something I'm set up to look into very well.

**Comment by melinath** [comment]
Kk, no worries. Looks good.

**Comment by willkg** [comment]
Thank you!

**Comment by melinath** [comment]
FTR: [bz19777](http://bugzilla.pculture.org/show_bug.cgi?id=19777)

**Pull request merged**
