### PR TITLE
Add a tox.ini for tox (http://tox.testrun.org/)

### PR DESCRIPTION
**Pull request by msabramo**

### CODE REVIEW

**Comment by melinath** [comment]
This looks nifty. I want to play with it a bit before merging, but I don't have time to do so atm. A cursory inspection leads me to believe that I should mention that vidscraper is intended to be tested with nose. Not sure if that makes a difference.

**Comment by msabramo** [comment]
Oh well then you might want to add `deps = nose` and optionally change `setup.py test` to `setup.py nosetests` or you could just call `nosetests` directly.

**Comment by melinath** [comment]
Is the tox.ini file working for you as is, without nose? (Working as in actually running all the tests.)

**Comment by msabramo** [comment]
Yep, it is. By the way, I also submitted a PR to add `tox` to mirocommunity -- see https://github.com/pculture/mirocommunity/pull/38

**Comment by melinath** [comment]
Yeah, I saw it. We'll probably merge it around the same time we merge this one.

I tried to google tox vs travis, and it came up with tox pull requests by you on a number of projects. Are you working on spreading the word about tox? Or do you just like it bunches?

**Comment by msabramo** [comment]
Here's the output of tox on my system: https://gist.github.com/2926382

**Comment by msabramo** [comment]
Haha. I didn't mean to establish a Google presence as "the tox guy" :-)

Tox and Travis are both great tools and testing and CI are important in my book and will be a big help porting packages to Python 3.

**Comment by melinath** [comment]
Tox looks great. I'd like to merge this in. Before I can do so, I need to have a [PCF CLA](mirocommunity.readthedocs.org/en/latest/_downloads/PCF__Contributor_Assignment_Agreement.pdf) from you emailed to legal@pculture.org. You'll only need to fill out the one CLA for Vidscraper and Miro Community.

**Comment by msabramo** [comment]
OK, I just sent the form in.

**Comment by melinath** [comment]
Thanks!

**Pull request merged**
