### PR TITLE
Feature/video index

### PR DESCRIPTION
**Pull request by paulswartz**

### CODE REVIEW

**Comment by melinath** [comment]
Looks good, mostly. AFAICT 4b5 and 0a5 are not really related to the branch - let me know if I'm wrong. The only thing that really troubles me, looking through it, is the get_start_index method.

It returns the total number of items in the feed or search, which is used in BaseVideoIterator.__iter__ to start the "index" for the videos that are found at the total number of videos and then count down.

There are a couple of problems with this:
1. There is already a meaning for "start_index" in relation to feeds - namely, the position of the first video on a page of a feed in the total feed.
2. In general, the "first" video in a feed is the "most recent" one - the top video on the first page of the feed. By counting down, we work against that basic way of looking at feeds.
3. The reason for the index counting down (IIRC) is that it lets the FeedImportIndex model in mirocommunity count a video's position in the _import_ by "when it was imported". So the last video gets imported "first" by having an index of one.
   - on principle: as much as possible, vidscraper should be treated as independent of mirocommunity.
   - If I understand correctly, the idea was to then order the FeedImportIndex items by this index. That doesn't actually seem to be the case currently. If it were - the same effect could be achieved with a descending sort on an index that started at one.

Switching the __reverse__ iteration to use a decreasing index also has the advantage that __reverse__ has an accurate count of the total number of videos that it's importing.

**Comment by melinath** [comment]
Looking at this a little more, it seems like the pickling may be intended to let vidscraper videos be serialized with celery. If that's the case, it should be mentioned that celery has serialization backends other than pickle, for which the videos will still not be serializable. It might be worthwhile to consider serializing the videos as dictionaries instead, which can easily be serialized with pickle, json, yaml, or other formats without additional work.

**Comment by paulswartz** [comment]
Yes, I could split this up, or I could also rename it; all the work was done as support for the Vidscraper-tasks-in-celery feature. It just turned out that more work needed to be done than just implementing the video index.

The advantage to counting down is that it works more effectively for feeds where we know the total number of items: YouTube, for example. There, counting down gives each video a unique index. You're correct that feeds are usually listed /in the feed/ ordered latest to first, they're generally numbered (guid, URL numbers, &c) in a way that gives newer videos higher IDs.

I implemented the get_start_index() method so that **iter** doesn't have to know about what kind of feed it's looking at. Since searches use most of the same code, it makes sense to give them the same kind of ID, even if MC isn't using it at the moment.

We could implement the serialization to a dict, but we'd still need to do basically the same thing I'm doing for the pickle case: represent everything as simple datatypes.  Since pickle is the default serialization for celery, I think this is good enough for now.

**Comment by melinath** [comment]
Counting up would also give each video a unique index, within the import. A lot of feeds only return, say, the 15 most recent videos, in which case counting down doesn't do any better. Since the videos already have ids or guids, we don't have to be responsible for providing a unique index over the _entire_ feed - besides, we can't guarantee that. If any videos were ever removed from the feed, the uniqueness would break. And again, the standard way of indexing videos in a feed (with the OpenSearch spec) is that start_index starts at 1 on the first page, then goes to say 21 on the second page, etc.

In terms of serializing to dictionaries, now would be a good time to do it, rather than intentionally creating a bug that will pop up later. As you said, it wouldn't be that much different from what you've already done. The main difference would be that the video state (such as the regex patterns) doesn't need to be preserved - only the field values need to be transferred.

**Comment by paulswartz** [comment]
Okay. Counting down makes more sense to me, but I'm not wedded to it, so I'll flip the order.

**Comment by paulswartz** [comment]
Oh, and the reason I haven't gotten the ordering into MC yet is because I don't quite understand how to interface it with the new search indexing code.  It doesn't have any tests anyways, so I guess I'll get to that later.

**Comment by melinath** [comment]
Mm. If you prefer, I can handle the interaction with the search indexing when it comes up. In any case, I don't think we should need it yet, since the search views haven't historically provided the option of viewing in feed order, and the admin review queue doesn't use the indexes.

**Comment by paulswartz** [comment]
They've historically /always/ sorted in that order, based on how we did the feed imports; replicating that behavior is why we needed to keep track of where videos were in the feed when we moved into Celery.

**Comment by melinath** [comment]
Right. Because of the submit date. My mistake. :-p

**Pull request merged**
