### PR TITLE
bz18936. strip country codes from YouTube descriptions

### PR DESCRIPTION
**Pull request by paulswartz**
Build: http://travis-ci.org/#!/pculture/vidscraper/builds/973356

### CODE REVIEW

**Comment by melinath** [comment]
I'd rather have a more complete way of handling this. The issue is caused by a bug in feedparser, which now has a [pull request](https://github.com/kurtmckee/feedparser/pull/4). However, the solution here is imperfect. Here's what we're solving:

> bestofattenboroughLike dolphins, whales communicate using sound. Humpbacks especially have extremely complex communication systems.youtubeBD BE BF BG BA BB WF BL BM BN BO BH BI BJ BT JM BV BW WS BR BS JE BY BZ RU RW RS LT RE LU LR RO LS GW GU GT GS GR GQ GP JP GY GG GF GE GD GB GA SV GN GM GL KW GI GH OM JO HR HT HU HK HN LV HM AD PR PS PW PT KR PY AI PA PF PG PE PK PH PN PL PM ZM EH EE EG ZA EC AL AO KZ ET ZW KY ES ER ME MD MG MF MA MC UZ MM ML MO MN MH US MU MT MW MV MQ MP MS MR AU UG MY MX VU FR IO AF AX FI FJ FK FM FO NI NL NO NA NC NE NF NG NZ NP NR NU CK CI CH CO CN CM CL CC CA CG CF CD CZ CY CX CR KP CV CU SZ SY KG KE ZZ SR KI KH KN KM ST SK SJ SI SH SO SN SM SL SC SB SA SG SE SD DO DM DJ DK DE YE AT DZ MK UY YT UM TZ LC LA TV TW TT TR LK LI TN TO TL TM TJ TK TH TF TG TD TC LY VA VC AE VE AG VG IQ VI IS IR AM IT VN AN AQ AS AR IM IL AW IN LB AZ IE ID UA QA MZ
- _bestofattenborough_: media:credit
- _Like dolphins..._: media:description
- _youtube_: media:license
- _BD BE..._: media:restriction

So what we would be doing is breaking the "description" up based on the username and the license. This doesn't seem like a good idea, since it'll choke (for example) on any video with a non-youtube license. Perhaps we should just wait until the pull request comes through. (or find a better way)

**Comment by melinath** [comment]
We're currently already pulling media:license information; can we split on that instead of hardcoding it on youtube?

**Comment by paulswartz** [comment]
We can't split on that, because that content isn't pulled into the `media_license` key.  I've added that to my pull request, but once that goes through the whole issue is moot.

Edit: once the pull request is merged and an updated feedparser is released the issue is moot.  We /could/ put a `requirements.txt` file in the repository so stuff like Travis will pull in  the development version or my version with the fix, but that won't affect people who 'pip install vidscraper`.

**Comment by melinath** [comment]
It seems that there's an [alternate solution](https://github.com/pculture/vidscraper/commit/16652d0fb84f4051fb57cf3e5c30a32988573066#diff-4) - use the json api instead of using feedparser. You could backport this into a 0.5.1 release, or we could just leave it til 0.6.

**Comment by paulswartz** [comment]
Good idea.  I've backported your changes into this branch.  It'd be nice to make a 0.5.1 release so that we can use it with the MC 1.8.2 release.

**Comment by melinath** [comment]
Could you also backport the part that uses the json api for feed parsing? Otherwise I'd be worried that a video instantiated from a feed might still have the same issues, since it wouldn't override the pre-loaded feed data.

**Comment by paulswartz** [comment]
Is there a reason to do that, given that everything gets refactored in 0.6?  I only backported this one because it fixes a user-visible bug.

**Comment by melinath** [comment]
It looks like the atom feed that youtube gets its items from might be different enough that it wouldn't have the same issues; if that's the case, I'm fine with putting it off until 1.6.

**Comment by paulswartz** [comment]
I'll investigate.

**Comment by paulswartz** [comment]
http://gdata.youtube.com/feeds/base/users/BestofAttenborough/uploads?alt=rss&v=2 is the feed which contains the video.

The description in the feed is HTML, but that's handled separately.  It doesn't include the country codes that the API feed does.

**Comment by paulswartz** [comment]
Just discovered a bug with this while running the MC tests (probably affects the other branch too).  Hold off on merging for now.

**Comment by paulswartz** [comment]
Fixed the bug, added a test, and everything's passing: http://travis-ci.org/#!/pculture/vidscraper/builds/1010966

**Pull request merged**
